### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by wolf99** [Cazzar/vscode-gradle#4]
I have a clean install of VS Code and Gradle on Win 10. I have run `>gradle init` in the working directory. `>gradle build` and >gradle run` work just fine from the command line. I have added `"gradle.useCommand": ".\\gradlew"` to `settings.json`.

If I try to build (Ctrl + Shift + B) VS Code shows:

> No build task defined. Mark a task with 'isBuildCommand' in the tasks.json file.

Do I need to write a build task? If so how should it be written? First time VS Code and Gradle user so having followed the info in the plugin's readme and googled a bit, I am now pretty much at a complete loss as to how to proceed further.

**Comment by Cazzar** [comment]
It's not a build task, this was implemented before build tasks were in place.
You run it as a normal command, `Ctrl+Shift+P` 

![image](https://cloud.githubusercontent.com/assets/994214/26522697/8ff443f4-4349-11e7-9f07-edb44d559a19.png)

**Comment by wolf99** [comment]
OK, that works. The readme could be update to show this kind of information maybe? 
How to run the thing might be considered worth more than a single image that doesn't actually show what is typed in the command line (the command line int he image in the readme is empty)...
